### ISSUE TITLE
suggestion widget take me to the top repeaditly

### ISSUE THREAD

**Issue by SAWKERAKAIJIELITE** [roerohan/vscode-MongoSnippets-NodeJS#38] opened 2023-09-16 14:20 UTC
Type: <b>Bug</b>

when suggestion widget appear and I sroll it by arrow keys, It returns me to the top of it.
for example, when I pressed dot notation, the suggestion widget appears and it is fine, but I want to explore other fields so I press down arrow button until I found it. but every 6 seconds, the suggestion widget refreshed and take me to the first choice.

Extension version: 1.3.12
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30835153
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by roerohan** [comment] 2023-09-27 05:18
Hi @SAWKERAKAIJIELITE 
This is a duplicate of #23

I don't think I'll be able to take a look at this issue anytime soon, if you want you can try to resolve this
I'll put this up for Hacktoberfest '23 as well

**Closed as completed by roerohan** 2023-09-27 05:18 UTC
